DROP TABLE IF EXISTS Platform;
DROP TABLE IF EXISTS Region;
DROP TABLE IF EXISTS Version;

DROP TABLE IF EXISTS RunnerRuns;
DROP TABLE IF EXISTS Runs;
DROP TABLE IF EXISTS Runner;

DROP TABLE IF EXISTS Games;
DROP TABLE IF EXISTS Category;


CREATE TABLE IF NOT EXISTS Games(
        GameId      INTEGER PRIMARY KEY,
        SRId        TEXT UNIQUE,
        GameName    TEXT,
        ShortName   TEXT
        );
