CREATE TABLE IF NOT EXISTS Runs(
    RunId          INTEGER PRIMARY KEY,
    SRId           TEXT UNIQUE,
    GameId         INTEGER,
    CategoryId     INTEGER,
    Time           TEXT,
    TimeSecs       REAL,
    PlatformId     INTEGER REFERENCES Platform(SRId),
    Emulated       INTEGER,
    RegionId       TEXT REFERENCES Region(SRId),
    VideoLink      TEXT,
    Comment        TEXT,
    SubmitDate     TEXT,
    Status         TEXT,
    Examiner       TEXT,
    VerifyDate     TEXT,
    RowCreatedDate TEXT,
    AlgPoint       INTEGER,
    Variables      TEXT
    );
