CREATE TABLE IF NOT EXISTS Runs(
    RunId INTEGER PRIMARY KEY,
    SRId TEXT UNIQUE,
    GameId INTEGER REFERENCES Games(id),
    CatId INTEGER REFERENCES Category(id),
    Time TEXT,
    TimeSecs REAL,
    PlatformId INTEGER REFERENCES Platform(id),
    Emulated INTEGER,
    RegionId TEXT REFERENCES Region(id),
    VideoLink TEXT,
    Comment TEXT,
    SubmitDate TEXT,
    Status TEXT,
    Examiner TEXT,
    VerifyDate TEXT,
    RowCreatedDate TEXT,
    AlgPoint INTEGER,
    Variables TEXT
);
