CREATE TABLE IF NOT EXISTS Runs(
    RunId          INTEGER PRIMARY KEY autoincrement,
    SRId           TEXT UNIQUE,
    GameId         TEXT,
    LevelId        TEXT,
    CategoryId     TEXT,
    RunnerId       INTEGER,
    RunnerSrcId    TEXT,
    Time           TEXT,
    TimeSecs       REAL,
    PlatformId     TEXT REFERENCES Platform(SRId),
    Emulated       INTEGER,
    RegionId       TEXT REFERENCES Region(SRId),
    VideoLink      TEXT,
    Comment        TEXT,
    SubmitDate     TEXT,
    Status         TEXT,
    Examiner       TEXT,
    VerifyDate     TEXT,
    RowUpdatedDate TEXT,
    AlgPoint       INTEGER,
    Variables      TEXT
    );
