name = "api"
main = "./src/index.ts"
compatibility_date = "2023-02-01"
node_compat = true
[[ d1_databases ]]
binding = "DB"
database_name = "jakspeedruns-db"
database_id = "30c599a9-94c6-450a-8783-47153c6bc277"
preview_database_name = "jakspeedruns-db-preview"
preview_database_id = "86455a6c-b816-4780-bf0a-da975d80c501"
