name = "jsr-backend"
main = "./src/index.ts"
compatibility_date = "2023-02-01"
node_compat = true
[[ d1_databases ]]
binding = "DB"
database_name = "jsr-backend-db"
database_id = "TODO"
# preview_database_name = ""
# preview_database_id = ""
